name: currency-cron
on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our Currency API route
        run: |
          curl --request PUT \
          --url 'https://api-asd123.vercel.app/api/currency' \
          --header 'Content-Type: application/json'
